<!-- 
    .csproj
	 - C# Project 파일
	 - C# 프로젝트가 어떤 환경과 설정으로 만들어지는지 정의
	 - 본 프로젝트를 어떤 방식으로 빌드해야 하는지 정의
	 
	주요 역할
	 - 사용할 .NET 버전 설정
	 - 프로그램 종류 설정
	 - WPF 사용 여부 설정
	 - 빌드 관련 설정 관리
	 - 외부 패키지 관리
	
	Build(빌드)
	 - 작성한 Source Code와 Resource 등을 처리하여
	   실행 가능한 프로그램을 만드는 전체 과정
	(1) 프로젝트 설정 확인
	(2) C# 코드 컴파일
	(3) XAML과 Resource 처리
	(4) 필요한 라이브러리 확인
	(5) 실행에 필요한 결과 파일
	
	Compile(컴파일)
	 - C# Source Code를 .NET이 실행할 수 있는
	   형태로 만드는 과정
-->
<Project Sdk="Microsoft.NET.Sdk">
  <!-- 
	Project : 현재 프로젝트 전체를 의미
	Sdk(SDK, Soft Development Kit)
	 : 프로그램 개발에 필요한 도구와 라이브러리를 모아 놓은 것
	Microsoft.NET.sdk
	 : .NET 프로젝트를 빌드할 때 사용하는 기본 SDK 
  -->	
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
